name: formulize
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  result_dart: ^1.0.5
  flutter_modular: ^5.0.3
  realm: ^1.0.3
  rx_notifier: ^2.2.2
  asuka: ^2.0.2
  loader_overlay: ^2.2.0
  uno: ^1.1.6
  intl: ^0.17.0
  localization: ^2.1.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutterando_analysis: ^0.0.2
  rx_notifier_generator: ^1.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - .env
